"""initial_schema

Revision ID: 048b50b598ce
Revises: d096be69e9d9
Create Date: 2026-03-09 14:22:01.813685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '048b50b598ce'
down_revision: Union[str, None] = 'd096be69e9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
