"""initial

Revision ID: d096be69e9d9
Revises: 469e8a2ad0bb
Create Date: 2026-03-08 02:11:40.696883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd096be69e9d9'
down_revision: Union[str, None] = '469e8a2ad0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
